<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### Your Name

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```


```{r}
Datos <- 
  readXL("C:/Users/alexm/Desktop/trabajos uni/SEGUNDO DE BIOLOGIA/Bioquímica 1/PRÁCTICAS DE LAB/practic bqca.xlsx",
   rownames=FALSE, header=TRUE, na="", sheet="Hoja3", stringsAsFactors=TRUE)
```

```{r}
RegModel.1 <- lm(Abs.400.nm~µmol.PNF, data=Datos)
summary(RegModel.1)
```


```{r}
attach(Datos)
```


```{r}
attach(Datos)
```

```{r}
plot(Abs.400.nm~µmol.PNF,data=Datos,main="Recta patrón PNF");abline(RegModel.1,
  col="gold")
```

```{r}
attach(Datos)
```


```{r}
plot(Abs.400.nm~µmol.PNF,data=Datos,main="Recta patrón PNF");abline(RegModel.1,
  col="gold")
```


```{r}
attach(Datos)
```

```{r}
attach(Datos)
```


```{r}
xnueva<-seq(min(µmol.PNF),max(µmol.PNF),length.out=100)
```


```{r}
xnueva
```


```{r}
ynueva<-predict(RegModel.1,newdata=data.frame(µmol.PNF=xnueva),
  interval="confidence")
```

```{r}
attach(Datos)
```


```{r}
xnueva<-seq(min(µmol.PNF),max(µmol.PNF),length.out=100)
```


```{r}
xnueva
```


```{r}
ynueva<-predict(RegModel.1,newdata=data.frame(µmol.PNF=xnueva))
```


```{r}
plot(Abs.400.nm~µmol.PNF,data=Datos,main="Recta patrón PNF");abline(RegModel.1,
  col="gold")
```


```{r}
attach(Datos)
```


```{r}
xnueva<-seq(min(µmol.PNF),max(µmol.PNF),length.out=100)
```


```{r}
xnueva
```


```{r}
ynueva<-predict(RegModel.1,newdata=data.frame(µmol.PNF=xnueva))
```


```{r}
plot(Abs.400.nm~µmol.PNF,data=Datos,main="Recta patrón PNF");abline(RegModel.1,
  col="gold")
```


